TASLabz/dolphin

- Source/Core/Core/API/Events.h
- Source/Core/Core/Core.cpp
- Source/Core/Core/State.cpp
- Source/Core/Core/State.h
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/RenderWidget.cpp
- Source/Core/Scripting/Python/Modules/eventmodule.cpp
- Source/Core/Scripting/Python/Modules/savestatemodule.cpp
Fires a new SaveStateLoad event on savestate slot/file load. Had to add an intermediary function to differentiate between the slot and file case, so that we assure one event firing per load scenario.
> SaveStateLoad callback/event

- Source/Core/Core/API/Events.h
- Source/Core/Core/Movie.cpp
- Source/Core/Core/State.cpp
- Source/Core/Core/State.h
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/Scripting/Python/Modules/eventmodule.cpp
- Source/Core/Scripting/Python/Modules/savestatemodule.cpp
- Fires a new SaveStateSave event on savestate slot/file save. Had to add an intermediary function to differentiate between the slot and file case, so that we assure one event firing per save scenario.
- Also moves event fire to occur AFTER state is saved/loaded. Due to timings, it would have been possible for the script to recognize a state load BEFORE it actually occurred. This could result in memory reads reflecting a point before the state load.
- Reorganize events to maintain constant order
- Keep consistent boolean naming convention
> SaveStateSave callback/event

- Source/Core/Core/API/Controller.cpp
- Source/Core/Core/API/Controller.h
- Source/Core/Core/HW/WiimoteEmu/Extension/Extension.h
- Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.h
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/Movie.cpp
- Source/Core/Core/Movie.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.h
- Source/Core/Scripting/Python/Modules/controllermodule.cpp
- Source/Core/Scripting/Python/PyScriptingBackend.cpp
- Source/Core/Scripting/Python/PyScriptingBackend.h
- Source/Core/Scripting/ScriptingEngine.cpp
- Adds two new API functions to get/set nunchuck stick and buttons
- controller.get_nunchuck_buttons and controller.set_nunchuck_buttons
- arguments to be updated in stub in next PR
- Remove unused arguments from Movie::PlayWiimote
Note: I could not find a reliable way to retrieve the current state of the nunchuck, so as an alternative I've opted to (if the controller is active) save the state of the nunchuck to the scripting module-managed class for the nunchuck.
> Add support to set/get Nunchuck buttons/stick

- Source/Core/Core/API/Events.h
- Source/Core/Core/State.cpp
Clang errors when these aren't explicitly define for some reason.
> Fix Compiling on Mac

- Source/Core/Scripting/Python/Modules/controllermodule.cpp
If we're passing inputs via set_gc_buttons, we obviously want the controller to be enabled. Current behavior is that if 'Connected' is not specified in the dictionary, then it will be set to False. This is silly. Get rid of this.
> Make controller default Connected when setting inputs

- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/Scripting/ScriptingWidget.cpp
- Source/Core/DolphinQt/Scripting/ScriptingWidget.h
- Source/Core/DolphinQt/Scripting/ScriptsListModel.cpp
- Source/Core/DolphinQt/Scripting/ScriptsListModel.h
- Primary goal is new toggle functionality, to determine whether or not a script is running
- Get rid of Name header as it serves no purpose really
- Change table label from Running scripts to Loaded scripts. This isn't entirely truthful, but it makes more sense since now they aren't always running
- Fix improper convention when adding/removing rows to the model
If we want to change name formatting since full URL looks ugly, then let's worry about that in a different PR after some more discussion.
> Script GUI changes

- Source/Core/DolphinQt/QtUtils/AspectRatioWidget.cpp
- Source/Core/DolphinQt/TAS/GCTASInputWindow.cpp
- Source/Core/DolphinQt/TAS/GCTASInputWindow.h
- Source/Core/DolphinQt/TAS/TASInputWindow.cpp
Before:--------------------------------------------------------------After:
This changes TAS Input to *mostly* match the window style from DolphinWx. The most important piece, in my opinion, is that it eliminates the unnecessarily excessive whitespace between the stick widget and the sliders.
> TAS Input Window Adjustments

- Source/Android/jni/MainAndroid.cpp
- Source/Core/Core/Core.cpp
- Source/Core/Core/Host.h
- Source/Core/DolphinNoGUI/MainNoGUI.cpp
- Source/Core/DolphinQt/Host.cpp
- Source/Core/DolphinQt/Host.h
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/TAS/TASInputWindow.cpp
- Source/Core/DolphinQt/TAS/TASInputWindow.h
- Source/DSPTool/StubHost.cpp
- Source/UnitTests/StubHost.cpp
These changes aim to allow hotkeys to be processed when TAS Input is the window of focus, regardless of whether or not the "Hotkeys Require Window Focus" hotkey is disabled/enabled. Previously, the only way you could frame advance with TAS Input is if you were ALSO able to frame advance when Discord, for example, is open. This is not optimal behavior, because we don't want random hotkeys to fire off by default when we are typing out Discord messages for example.
Note that these changes remove the use of the Host_UIBlocksControllerState() function, because of an edge case discovered with my changes. If you hold down a hotkey and switch from TAS Input to the game render widget, ImGUI can end up in a state where it will permanently not process keyboard inputs. I'm not quite sure what the …
> Allow hotkeys when TAS Input is window-of-focus

- Source/Core/DolphinQt/TAS/IRWidget.cpp
- Source/Core/DolphinQt/TAS/StickWidget.cpp
This appears to reduce window latency issues encountered when holding down frame advance and rotating the stick at the same time. It does not get rid of the latency, but definitely reduces it.
> DolphinQt: Limit TAS window stick signals/redraws

- Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
[NOTE: THIS IS ALSO IN A CURRENTLY OPEN PR IN UPSTREAM DOLPHIN. WE MAY WANT TO WAIT FOR POSSIBLE SUGGESTIONS IN ORDER TO AVOID MERGE CONFLICTS DOWN THE LINE.]
In the constructor of MemoryViewWidget we connect the Settings::EmulationStateChanged signal to MemoryViewWidget::UpdateColumns(). This poses a problem with TASing because a frame advance step implicitly changes the emulation state. When we hold down the frame advance key, this signal is then fired multiple times in quick succession.
On every instance that this signal is fired, it turns out that UpdateColumns() would wait to acquire the CPU lock and begin re-writing data in the memory view table, even if the debugging UI was not enabled. This extra time spent acquiring the CPU lock would cause TAS Input windows to become …
> DolphinQt: Prevent MemoryViewWidget updates when hidden

- Source/Core/Core/Config/MainSettings.cpp
Considering that this fork is intended for TASes, it makes sense (to me) to set this default to false. When enabled, dual core is pretty much guaranteed to cause .dtm desyncs. Truth be told the only TAS-related instance where this setting doesn't matter is Mario Kart Wii, since we use the in-game ghost system. However, script reliability is also dependent on this setting being disabled. So I don't see any drawbacks here.
> Config: Disable Dual Core by default

- Tools/lint-python-stubs.sh
- requirements-tests.txt
A very simple, config-less script to format, lint and type-check the python stubs. The same could be expanded for the entire project (but then I'd use a `project.toml` config file)
I added a `requirements` file with the necessary dependencies for testing.
The [Pyright python wrapper](https://pypi.org/project/pyright/) just installs node and highjacks the Pyright command, may as well install node yourself using your favorite package manager (or downloading the installer from their website).
The `npx` command checks if the package is already installed at that specific version, (in local and global `node_modules`), if not, it installs it globally then executes.
Of course linting will fail until #16 is merged.
> Script to lint and type-check python-stubs

- Source/Core/Core/Core.cpp
- Source/Core/Core/HW/VideoInterface.cpp
The long awaited fix to issue https://github.com/TASLabz/dolphin/issues/12
Looks like we need to fire the frame advance event at a different point. Someone in Dolphin's Discord server pointed out that they have a fork which signals frame advance occurrences in `Callback_NewField`, and this seems to fix the issue. Note that this means we can now remove the hacky solution from pianoroll.py: https://github.com/TASLabz/mkw-scripts/blob/main/scripts/pianoroll_player.py
> API: Fix timing of frame advance event firing

- Source/Core/DolphinQt/MainWindow.cpp
This fixes the following behavior I encountered.
Emulation > Save State > Save State to File. Close dialog without setting filename
Observe on-screen message "Saving state to " (no filepath given), and observe xxxxx.tmp file being created in main Dolphin directory
Repeat step 1 and 2 to observe more .tmp files being created
Start Movie Recording, repeat step 1 to now also see blank ".dtm" file present
Looks like Dolphin will always write savestate data to a temp file and then try to rename it. Ultimately when the provided filename is blank (because the QFileDialog was closed without the name being set) the rename will fail and the temp file will remain.
I figured this filename check should also be done for the load state scenario, as all this does is prevent a load failure in LoadAs().
> Qt: Prevent savestate load/save on empty filename

- Source/Core/DolphinQt/Scripting/ScriptingWidget.cpp
- Source/Core/DolphinQt/Scripting/ScriptingWidget.h
- Source/Core/DolphinQt/Scripting/ScriptsListModel.cpp
This addresses https://github.com/TASLabz/dolphin/issues/60 and https://github.com/TASLabz/dolphin/issues/52
New functionality:
- Removing a script that's enabled will cause the script to stop running (It would continue to run post-mortem before!)
- Allow multi-selecting of scripts in list
- Pressing delete key on selection of scripts will remove all scripts from the list (and stop and actively running ones)
- Pressing enter key on selection of scripts will toggle enable/disable them.
> ScriptingWidget improvements

- Source/Core/Core/API/Events.h
This addresses [C2666](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2666?view=msvc-170) when using the latest MSVC version.
This is cherry-picked from felk, who I observe had the same issue before.
> fix compile issues for newer versions of Visual Studio

- Source/Core/DolphinQt/TAS/TASInputWindow.cpp
- Source/Core/DolphinQt/TAS/TASInputWindow.h
Previously I had addressed this in https://github.com/TASLabz/dolphin/pull/26, but the window is considered going out-of-focus if you click on one of its child widgets, such as the face buttons. So while opening the TAS Input Window would allow you to use hotkeys at first, clicking a child widget would prevent it from working for the lifetime of the window.
This opts to use an eventFilter instead, looking for the WindowActivate and WindowDeactivate events. Hotkeys now work regardless of how you manipulate or interact with the TAS Input Window.
> Fix TAS Input Window hotkey focus issues

- Source/Core/DolphinQt/DolphinQt.vcxproj
- Source/Core/Scripting/Scripting.vcxproj
- Source/dolphin-emu.sln
Previously we had to manually build nfd THEN Scripting THEN Dolphin. I finally figured out how to fix this.
Tested by:
1. Clean Project. Build Dolphin
2. Clean Project. Build Solution
In both scenarios, I now compile successfully.
> Fix Visual Studio build order

- Source/Core/DolphinQt/TAS/TASInputWindow.cpp
Bringing back the old functionality we're all used to: TAS Input Window staying on-top at all times. However, for those who don't like this feature, I've also enabled the ability the minimize the window. Bringing the window back results in it remaining on-top again.
> DolphinQt: Keep TASInputWindow on top, allow minimize

- Source/Core/DolphinQt/MenuBar.cpp
- Source/Core/DolphinQt/MenuBar.h
- Source/Core/DolphinQt/Scripting/ScriptingWidget.cpp
- Source/Core/DolphinQt/Scripting/ScriptingWidget.h
- Source/Core/DolphinQt/Settings.cpp
The user should always be able to (easily) access the Scripting menu, even if debugging UI is not enabled. Scripting is not a debugging-related feature. Previously you had to right click on a currently visible dock object (such as Logs) and use the context menu to navigate to Scripting widgets.
Closing the Scripting widget also would not update the View->Scripting tab (when it was visible with debug enabled at least). So I fixed that as well.
My changes also prevent Dolphin from always opening the Scripting menu on startup. It will now remember whether you last had it enabled/disabled and keep it that until you change it again.
> DolphinQt: Allow View->Scripting regardless of debugging UI toggle

- Source/Core/Core/HW/AddressSpace.cpp
See https://github.com/dolphin-emu/dolphin/pull/12193
This fixes not being able to search memory within MEM2 effective address space.
> Debugger/Memory: Fix unable to search mem2

- Source/Core/Scripting/Python/PyScriptingBackend.cpp
https://github.com/TASLabz/mkw-scripts/pull/29 removes the need to add the Modules directory to the Python PATH. The Scripts directory is all we need.
> Scripting: Remove Modules dir from path

- Source/Core/Core/API/Memory.h
- Source/Core/Core/PowerPC/MMU.cpp
- Source/Core/Core/PowerPC/MMU.h
- Source/Core/Scripting/Python/Modules/memorymodule.cpp
- python-stubs/dolphin_memory.pyi
This adds 2 new functions to the memory module:
- `memory.read_bytes(addr, size)`
- `memory.write_bytes(addr, bytes)` where bytes is a Python `bytearray` object.
I found that it was annoying to read arbitrary number of bytes, such as pulling the Mii data struct byte-by-byte. Instead, this function will allow the user to query Dolphin for a certain number of bytes, and it will return a Python `bytearray`. I went with this as opposed to a `bytes` object, as I think `bytearray` allows for more easy manipulation of the data contained within.
Note that `MMU::ReadFromHardware` contains a translation check to prevent reads from invalid memory. The result is that it will return 0x00 for that byte. **We could debate whether to only return a bytearray with length equal to the number of bytes read …
> Scripting: Add read_bytes to memory module

- Source/Core/DolphinQt/Scripting/ScriptingWidget.cpp
- Source/Core/DolphinQt/Scripting/ScriptingWidget.h
Works on Windows/Mac/Linux and presumably Linux (awaiting Gaberboo). Simply opens to the Scripts directory.
> ScriptingWidget:: Add open folder button

- Source/Core/Common/Logging/LogManager.cpp
This aims to help users get debug help easier, as the settings they need to see errors generated by scripts will be on by default.
> Update log configuration defaults

- Source/Core/Scripting/CMakeLists.txt
- Source/Core/Scripting/Python/Modules/debugmodule.cpp
- Source/Core/Scripting/Python/Modules/debugmodule.h
- Source/Core/Scripting/Python/Modules/dolphinmodule.cpp
- Source/Core/Scripting/Python/Modules/utilmodule.cpp
- Source/Core/Scripting/Python/PyScriptingBackend.cpp
- Source/Core/Scripting/Scripting.vcxproj
- Source/Core/Scripting/Scripting.vcxproj.filters
- python-stubs/dolphin_debug.pyi
- python-stubs/dolphin_utils.pyi
I will need further testing, possibly by @vabold to verify the integrity of my implementations here.
Add the ability to set/remove BPs and memory BPs. Memory BPs can be created for a given address, or for a range of address, and can be configured equally as much as via the debugger UI.
Given that hitting BPs pauses the game, I also added a toggle_play function as well to resume after hit. This can be done by responding to the @event.memorybreakpoint or codebreakpoint callbacks.
I didn't know how to define the possible dictionary schema in the stub. Hopefully how I have it is fine.
> Scripting: Add debug module and toggle play function

- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/MainWindow.h
- Source/Core/DolphinQt/ToolBar.cpp
- Source/Core/DolphinQt/ToolBar.h
Given that Scripting is the main use of this build, it makes sense to have it quickly accessible via the toolbar. I used a pre-existing icon that I don't believe is used anywhere???
> Scripting: Add toolbar button

- Source/Core/Core/GeckoCodeConfig.cpp
If the gameID starts with RMC, then pull codes from mkwtas.com. This is not immediately mergeable because boumi has a typo in the sample endpoint. Only after the typo is fixed, and other regions are added+validated will this be eligible for merge.
This fixes https://github.com/TASLabz/dolphin/issues/44
> Get MKWii Gecko Codes from mkwtas.com

- Source/Core/DolphinQt/Scripting/ScriptingWidget.cpp
- Source/Core/DolphinQt/Scripting/ScriptingWidget.h
No game booted..................................................................MKWii booted
This should not be mergeable until appropriate changes are made to the scripts directory structure. We probably want to merge https://github.com/TASLabz/mkw-scripts/pull/41 first and then move scripts around to the RMC folder before merging this PR.
> Qt: Change script view to gameid directory on booting game up

- docs/PythonScripting.md
This fixes https://github.com/TASLabz/dolphin/pull/110
This document explains how to make your own scripts and explains the folder hierarchy Dolphin expects.
This is based off of changes that are made in https://github.com/TASLabz/dolphin/pull/104 so that should be merged before this.
> Docs: Add Scripting documentation
